### ISSUE TITLE
프론트 To-do

### ISSUE THREAD

**Issue by yayshine** [Nexters/flass#58]
**보빈**

- [ ] 1. 강의정보
- [ ] 2. 댓글
- [ ] 3. 로그아웃
- [ ] 4. 홈 화면 호버, 클릭 처리
- [ ] 5. 분석 (가능하면)

**주형**

- [ ] 1. 로그인 HOC 처리
- [ ] 2. 업로드 모달
- [ ] 3. 분석
- [ ] 

**예훈**

- [ ] 1. rem 비율 계산
- [ ] 2. 업로드 기능 합체
- [ ] 3. 업로드 CSS
- [ ] 4. 로그인 UI
- [ ] 5. 알람

**Comment by zeroFruit** [comment]
----------------------------NEXTERS 정기활동 끝------------------------------------

**Comment by zeroFruit** [comment]
**보빈**

- [ ] 1. 강의정보
- [ ] 2. 댓글
- [ ] 3. 로그아웃
- [ ] 4. 홈 화면 호버, 클릭 처리
- [ ] 5. 분석 (가능하면)

**주형**

- [ ] 1. 비디오 CSS 처리
- [ ] 2. 링크타고 학생용 디테일 화면 넘어가기 작업
- 3. 분석(보빈형에게로 넘어감)

**예훈**

- [x] 1. rem 비율 계산
- [x] 2. 업로드 기능 합체
- [x] 3. 업로드 CSS
- [x] 4. 로그인 UI
- [ ] 5. 알람
- [ ] 6. CSS 호버,클릭 처리

* 우선 순위 순번
